baseurl = "http://kyleperkuhn.com"
googleAnalytics = "UA-XXXXX-Y"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Hugo Identity Theme"
[params]
appletouchicon = "apple-touch-icon-precomposed.png"
avatar = "kyle.jpg"
background = "bg1.jpg"
email = "your@email.com"
favicon = "favicon.ico"
name = "Kyle Perkuhn"
position = "Product Manager"
[params.contact]
buttonText = "Send"
emailPlaceholder = "Email"
enable = true
formTitle = "Email Me"
messagePlaceholder = "Message"
namePlaceholder = "Name"
[params.footer]
copyright = "Kyle Perkuhn"
[[params.social]]
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/kyleperkuhn"
title = "LinkedIn"
[[params.social]]
icon = "fa-facebook"
link = "https://www.facebook.com/kyle.perkuhn"
title = "Facebook"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/KylePerkuhn"
title = "Twitter"
