baseurl = "https://kyleperkuhn.com"
googleAnalytics = "UA-XXXXX-Y"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Kyle Perkuhn"
[params]
appletouchicon = "/forestryio/images/apple-icon-180x180.png"
avatar = "kyle.jpg"
background = "bg1.jpg"
company = "Thunderhead Engineering"
email = "your@email.com"
favicon = "/forestryio/images/favicon-32x32.png"
location = "Austin, TX"
name = "Kyle Perkuhn"
position = "Product Manager"
[params.contact]
buttonText = "Send"
emailPlaceholder = "Email"
enable = false
formTitle = "Email Me"
messagePlaceholder = "Message"
namePlaceholder = "Name"
[params.footer]
copyright = "Kyle Perkuhn"
[[params.social]]
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/kyleperkuhn"
title = "LinkedIn"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/KylePerkuhn"
title = "Twitter"
[[params.social]]
icon = "fa-github"
link = "https://github.com/kyleperkuhn"
title = "GitHub"
